/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.registration.controller;

import com.example.registration.dto.AccountNotFoundError;
import com.example.registration.dto.Equipment;
import com.example.registration.dto.EquipmentRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;

import java.util.List;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-24T12:07:16.384698600+04:00[Asia/Dubai]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "Equipment", description = "the Equipment API")
public interface EquipmentsApi {

    /**
     * GET /equipments : Equipment list
     *
     * @return List returned successfully (status code 200)
     *         or Equipment not found (status code 404)
     */
    @Operation(
        operationId = "equipmentsGet",
        summary = "Equipment list",
        tags = { "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List returned successfully", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Equipment.class)))
            }),
            @ApiResponse(responseCode = "404", description = "Equipment not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AccountNotFoundError.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/equipments",
        produces = { "application/json" }
    )
    ResponseEntity<List<Equipment>> equipmentsGet();


    /**
     * DELETE /equipments/{id} : Delete equipment
     *
     * @param id  (required)
     * @return Equipment removed (status code 204)
     */
    @Operation(
        operationId = "equipmentsIdDelete",
        summary = "Delete equipment",
        tags = { "Equipment" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Equipment removed")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/equipments/{id}"
    )
    ResponseEntity<Void> equipmentsIdDelete(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id")Integer id
    );


    /**
     * GET /equipments/{id} : Get equipment by ID
     *
     * @param id  (required)
     * @return Equipment found (status code 200)
     *         or Equipment not found (status code 404)
     */
    @Operation(
        operationId = "equipmentsIdGet",
        summary = "Get equipment by ID",
        tags = { "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Equipment found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Equipment.class))
            }),
            @ApiResponse(responseCode = "404", description = "Equipment not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/equipments/{id}",
        produces = { "application/json" }
    )
    ResponseEntity<Equipment> equipmentsIdGet(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id")Integer id
    );


    /**
     * PUT /equipments/{id} : Update equipment
     *
     * @param id  (required)
     * @param equipmentRequest  (required)
     * @return Updated equipment (status code 200)
     */
    @Operation(
        operationId = "equipmentsIdPut",
        summary = "Update equipment",
        tags = { "Equipment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated equipment", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Equipment.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/equipments/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Equipment> equipmentsIdPut(
            @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id")Integer id,
            @Parameter(name = "EquipmentRequest", description = "", required = true) @Valid @RequestBody EquipmentRequest equipmentRequest
    );


    /**
     * POST /equipments : Add new equipment
     *
     * @param equipmentRequest  (required)
     * @return Equipment successfully created (status code 201)
     */
    @Operation(
        operationId = "equipmentsPost",
        summary = "Add new equipment",
        tags = { "Equipment" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Equipment successfully created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Equipment.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/equipments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Equipment> equipmentsPost(
            @Parameter(name = "EquipmentRequest", description = "", required = true) @Valid @RequestBody EquipmentRequest equipmentRequest
    );

}
